# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171106_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True, verbose_name='\u6587\u7ae0\u7b80\u4ecb'),
        ),
    ]
