# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='clicked',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, verbose_name='\u6807\u7b7e\u540d'),
        ),
    ]
