# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20171211_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(null=True, to='article.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
