# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20171211_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='upload_img/orange.jpg', upload_to='upload_img/%Y/%m', verbose_name='\u56fe\u7247'),
        ),
    ]
