# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u65b0\u95fb',
                'verbose_name_plural': '\u9996\u9875\u65b0\u95fb',
            },
        ),
    ]
