# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
