# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 03:05
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_delete_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
