# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 16:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20171215_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
